---
name: Matrix CI

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  yamllint:
    name: 🧹 yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v3
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@v1.2.0
